---
- hosts: all

  pre_tasks:
    - import_tasks: tasks/users.yml
      tags: users

  roles:
    - role: bertvv.samba
      tags:
        - samba
        - skip_ansible_lint

    - role: geerlingguy.nfs
      tags:
        - nfs
        - skip_ansible_lint

    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint

    - role: stefangweichinger.ansible_rclone
      tags:
        - rclone
      when: (rclone_enabled | default(False))

    - role: sprat.mergerfs
      tags:
        - mergerfs
      when: (mergerfs_enabled | default(False))

    - role: arillso.restic
      tags:
        - restic
      when: (restic_enabled | default(False))

  tasks:
  - import_tasks: tasks/general.yml
    tags: general

  - import_tasks: tasks/docker.yml
    tags: docker

  - import_tasks: tasks/portainer.yml
    when: (portainer_enabled | default(False))
    tags: portainer

  - import_tasks: tasks/traefik.yml
    when: (traefik_enabled | default(False))
    tags: traefik

  - import_tasks: tasks/heimdall.yml
    when: (heimdall_enabled | default(False))
    tags: heimdall

  - import_tasks: tasks/organizr.yml
    when: (organizr_enabled | default(False))
    tags: organizr

  - import_tasks: tasks/watchtower.yml
    when: (watchtower_enabled | default(False))
    tags: watchtower

  - import_tasks: tasks/plex.yml
    when: (plex_enabled | default(False))
    tags: plex

  - import_tasks: tasks/firefly.yml
    when: (firefly_enabled | default(False))
    tags: firefly

  - import_tasks: tasks/emby.yml
    when: (emby_enabled | default(False))
    tags: emby

  - import_tasks: tasks/tautulli.yml
    when: (tautulli_enabled | default(False))
    tags: tautulli

  - import_tasks: tasks/transmission.yml
    when: (transmission_enabled | default(False))
    tags: transmission

  - import_tasks: tasks/transmission_with_openvpn.yml
    when: (transmission_with_openvpn_enabled | default(False))
    tags: transmission

  - import_tasks: tasks/pyload.yml
    when: (pyload_enabled | default(False))
    tags: pyload

  - import_tasks: tasks/thelounge.yml
    when: (thelounge_enabled | default(False))
    tags: thelounge

  - import_tasks: tasks/mylar.yml
    when: (mylar_enabled | default(False))
    tags: mylar

  - import_tasks: tasks/sonarr.yml
    when: (sonarr_enabled | default(False))
    tags: sonarr

  - import_tasks: tasks/radarr.yml
    when: (radarr_enabled | default(False))
    tags: radarr

  - import_tasks: tasks/glances.yml
    when: (glances_enabled | default(False))
    tags: glances

  - import_tasks: tasks/netdata.yml
    when: (netdata_enabled | default(False))
    tags: netdata

  - import_tasks: tasks/duplicati.yml
    when: (duplicati_enabled | default(False))
    tags: duplicati

  - import_tasks: tasks/couchpotato.yml
    when: (couchpotato_enabled | default(False))
    tags: couchpotato

  - import_tasks: tasks/sickchill.yml
    when: (sickchill_enabled | default(False))
    tags: sickchill

  - import_tasks: tasks/znc.yml
    when: (znc_enabled | default(False))
    tags: znc

  - import_tasks: tasks/miniflux.yml
    when: (miniflux_enabled | default(False))
    tags: miniflux

  - import_tasks: tasks/nextcloud.yml
    when: (nextcloud_enabled | default(False))
    tags: nextcloud

  - import_tasks: tasks/gitea.yml
    when: (gitea_enabled | default(False))
    tags: gitea

  - import_tasks: tasks/gitlab.yml
    when: (gitlab_enabled | default(False))
    tags: gitlab

  - import_tasks: tasks/timemachine.yml
    when: (timemachine_enabled | default(False))
    tags: timemachine

  - import_tasks: tasks/stats.yml
    when: (stats_enabled | default(False))
    tags: stats

  - import_tasks: tasks/guacamole.yml
    when: (guacamole_enabled | default(False))
    tags: guacamole

  - import_tasks: tasks/airsonic.yml
    when: (airsonic_enabled | default(False))
    tags: airsonic

  - import_tasks: tasks/cloudflare_ddns.yml
    when: (cloudflare_ddns_enabled | default(False))
    tags: cloudflare_ddns

  - import_tasks: tasks/minidlna.yml
    when: (minidlna_enabled | default(False))
    tags: minidlna

  - import_tasks: tasks/get_iplayer.yml
    when: (get_iplayer_enabled | default(False))
    tags: get_iplayer

  - import_tasks: tasks/mymediaforalexa.yml
    when: (mymediaforalexa_enabled | default(False))
    tags: mymediaforalexa

  - import_tasks: tasks/jackett.yml
    when: (jackett_enabled | default(False))
    tags: jackett

  - import_tasks: tasks/joomla.yml
    when: (joomla_enabled | default(False))
    tags: joomla

  - import_tasks: tasks/vaultwarden.yml
    when: (vaultwarden_enabled | default(False))
    tags: vaultwarden

  - import_tasks: tasks/nzbget.yml
    when: (nzbget_enabled | default(False))
    tags: nzbget

  - import_tasks: tasks/wallabag.yml
    when: (wallabag_enabled | default(False))
    tags: wallabag

  - import_tasks: tasks/mosquitto.yml
    when: (mosquitto_enabled | default(False))
    tags: mosquitto

  - import_tasks: tasks/homebridge.yml
    when: (homebridge_enabled | default(False))
    tags: homebridge

  - import_tasks: tasks/calibre.yml
    when: (calibre_enabled | default(False))
    tags: calibre

  - import_tasks: tasks/homeassistant.yml
    when: (homeassistant_enabled | default(False))
    tags: homeassistant

  - import_tasks: tasks/bazarr.yml
    when: (bazarr_enabled | default(False))
    tags: bazarr

  - import_tasks: tasks/openhab.yml
    when: (openhab_enabled | default(False))
    tags: openhab

  - import_tasks: tasks/jellyfin.yml
    when: (jellyfin_enabled | default(False))
    tags: jellyfin

  - import_tasks: tasks/cloudcmd.yml
    when: (cloudcmd_enabled | default(False))
    tags: cloudcmd

  - import_tasks: tasks/krusader.yml
    when: (krusader_enabled | default(False))
    tags: krusader

  - import_tasks: tasks/ubooquity.yml
    when: (ubooquity_enabled | default(False))
    tags: ubooquity

  - import_tasks: tasks/utorrent.yml
    when: (utorrent_enabled | default(False))
    tags: utorrent

  - import_tasks: tasks/ombi.yml
    when: (ombi_enabled | default(False))
    tags: ombi

  - import_tasks: tasks/lidarr.yml
    when: (lidarr_enabled | default(False))
    tags: lidarr

  - import_tasks: tasks/youtubedlmaterial.yml
    when: (youtubedlmaterial_enabled | default(False))
    tags: youtubedlmaterial

  - import_tasks: tasks/serposcope.yml
    when: (serposcope_enabled | default(False))
    tags: serposcope

  - import_tasks: tasks/virtual_desktop.yml
    when: (virtual_desktop_enabled | default(False))
    tags: virtual_desktop

  - import_tasks: tasks/pytivo.yml
    when: (pytivo_enabled | default(False))
    tags: pytivo

  - import_tasks: tasks/nzbhydra2.yml
    when: (nzbhydra2_enabled | default(False))
    tags: nzbhydra2

  - import_tasks: tasks/sabnzbd.yml
    when: (sabnzbd_enabled | default(False))
    tags: sabnzbd

  - import_tasks: tasks/lazylibrarian.yml
    when: (lazylibrarian_enabled | default(False))
    tags: lazylibrarian

  - import_tasks: tasks/booksonic.yml
    when: (booksonic_enabled | default(False))
    tags: booksonic

  - import_tasks: tasks/booksonic-air.yml
    when: (booksonicair_enabled | default(False))
    tags: booksonicair

  - import_tasks: tasks/rclone.yml
    when: (rclone_enabled | default(False))
    tags: rclone

  - import_tasks: tasks/mergerfs.yml
    when: (mergerfs_enabled | default(False))
    tags: mergerfs

  - import_tasks: tasks/cloud_upload.yml
    when: (cloud_upload_enabled | default(False))
    tags: cloud_upload

  - import_tasks: tasks/syncthing.yml
    when: (syncthing_enabled | default(False))
    tags: syncthing

  - import_tasks: tasks/grocy.yml
    when: (grocy_enabled | default(False))
    tags: grocy

  - import_tasks: tasks/fstab.yml
    when: (fstab_enabled | default(False))
    tags: fstab

  - import_tasks: tasks/plex_autoscan.yml
    when: (plex_autoscan_enabled | default(False))
    tags: plex_autoscan

  - import_tasks: tasks/gaps.yml
    when: (gaps_enabled | default(False))
    tags: gaps

  - import_tasks: tasks/huginn.yml
    when: (huginn_enabled | default(False))
    tags: huginn

  - import_tasks: tasks/hs110.yml
    when: (hs110_enabled | default(False))
    tags: hs110

  - import_tasks: tasks/snipeit.yml
    when: (snipeit_enabled | default(False))
    tags: snipeit

  - import_tasks: tasks/shaarli.yml
    when: (shaarli_enabled | default(False))
    tags: shaarli

  - import_tasks: tasks/nodered.yml
    when: (nodered_enabled | default(False))
    tags: nodered

  - import_tasks: tasks/mariadb.yml
    when: (mariadb_enabled | default(False))
    tags: mariadb

  - import_tasks: tasks/seafile.yml
    when: (seafile_enabled | default(False))
    tags: seafile

  - import_tasks: tasks/phpmyadmin.yml
    when: (phpmyadmin_enabled | default(False))
    tags: phpmyadmin

  - import_tasks: tasks/errors.yml
    when: (errorpages_enabled | default(False))
    tags: errorpages

  - import_tasks: tasks/flarum.yml
    when: (flarum_enabled | default(False))
    tags: flarum

  - import_tasks: tasks/restic.yml
    when: (restic_enabled | default(False))
    tags: restic

  - import_tasks: tasks/ttrss.yml
    when: (ttrss_enabled | default(False))
    tags: ttrss

  - import_tasks: tasks/openldap.yml
    when: (openldap_enabled | default(False))
    tags: openldap

  - import_tasks: tasks/speedtest.yml
    when: (speedtest_enabled | default(False))
    tags: speedtest

  - import_tasks: tasks/webtrees.yml
    when: (webtrees_enabled | default(False))
    tags: webtrees

  - import_tasks: tasks/photoprism.yml
    when: (photoprism_enabled | default(False))
    tags: photoprism

  - import_tasks: tasks/photostructure.yml
    when: (photostructure_enabled | default(False))
    tags: photostructure

  - import_tasks: tasks/librephotos.yml
    when: (librephotos_enabled | default(False))
    tags: librephotos

  - import_tasks: tasks/whoogle.yml
    when: (whoogle_enabled | default(False))
    tags: whoogle

  - import_tasks: tasks/barcodebuddy.yml
    when: (barcodebuddy_enabled | default(False))
    tags: barcodebuddy

  - import_tasks: tasks/beets.yml
    when: (beets_enabled | default(False))
    tags: beets

  - import_tasks: tasks/ghost.yml
    when: (ghost_enabled | default(False))
    tags: ghost

  - import_tasks: tasks/moviematch.yml
    when: (moviematch_enabled | default(False))
    tags: moviematch

  - import_tasks: tasks/graylog.yml
    when: (graylog_enabled | default(False))
    tags: graylog

  - import_tasks: tasks/netbox.yml
    when: (netbox_enabled | default(False))
    tags: netbox

  - import_tasks: tasks/keycloak.yml
    when: (keycloak_enabled | default(False))
    tags: keycloak

  - import_tasks: tasks/traefik-forward-auth.yml
    when: (traefik_forward_auth_enabled | default(False))
    tags: traefik-forward-auth

  - import_tasks: tasks/authelia.yml
    when: (authelia_enabled | default(False))
    tags: authelia

  - import_tasks: tasks/komga.yml
    when: (komga_enabled | default(False))
    tags: komga

  - import_tasks: tasks/flame.yml
    when: (flame_enabled | default(False))
    tags: flame

  - import_tasks: tasks/ghost_default.yml
    when: (ghost_enabled | default(False))
    tags: ghost_default

  - import_tasks: tasks/gotify.yml
    when: (gotify_enabled | default(False))
    tags: gotify

  - import_tasks: tasks/prowlarr.yml
    when: (prowlarr_enabled | default(False))
    tags: prowlarr

  - import_tasks: tasks/netbootxyz.yml
    when: (netbootxyz_enabled | default(False))
    tags: netbootxyz

  - import_tasks: tasks/authentik.yml
    when: (authentik_enabled | default(False))
    tags: authentik

  - import_tasks: tasks/minetest.yml
    when: (minetest_enabled | default(False))
    tags: minetest

  - import_tasks: tasks/frigate.yml
    when: (frigate_enabled | default(False))
    tags: frigate

  - import_tasks: tasks/kavita.yml
    when: (kavita_enabled | default(False))
    tags: kavita

  - import_tasks: tasks/claper.yml
    when: (claper_enabled | default(False))
    tags: claper

  - import_tasks: tasks/ssh_login_notification.yml
    when: (ssh_login_notification_enabled | default(False))
    tags: ssh_login_notification

  - import_tasks: tasks/codex.yml
    when: (codex_enabled | default(False))
    tags: codex

  - import_tasks: tasks/releasebell.yml
    when: (releasebell_enabled | default(False))
    tags: releasebell

  - import_tasks: tasks/trilium.yml
    when: (trilium_enabled | default(False))
    tags: trilium