---
- hosts: all
  tasks:
  - name: Warning!
    debug:
      msg: "This playbook will repermission ALL existing data in the shares defined in group_vars/all.yml to be owned by the anarion-nas user and group. If this is not what you want, exit now."

  - name: 20s to change your mind...
    pause:
      seconds: 20

  - name: "Permission share data"
    file:
      path: "{{ item.path }}"
      owner: anarion-nas
      group: anarion-nas
      mode: "u=rwX,g=rwX,o=rX"
      recurse: true
    loop: "{{ samba_shares }}"


