- name: Create Bitwarden Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bitwarden_data_directory }}"

- name: Template bitwarden config.json
  template:
    src: bitwarden_rs/config.json
    dest: "{{ bitwarden_data_directory }}/config.json"

- name: Bitwarden Docker Container
  docker_container:
    name: bitwarden
    image: bitwardenrs/server:latest
    pull: true
    ports:
      - "{{ bitwarden_port_a }}:80"
      - "{{ bitwarden_port_b }}:3012"
    volumes:
      - "{{ bitwarden_data_directory }}:/data:rw"
    env:
      SIGNUPS_ALLOWED: "{{ bitwarden_allow_signups }}"
      ADMIN_TOKEN: "{{ bitwarden_admin_token }}"
      LOG_FILE: "/data/bitwarden.log"
      WEBSOCKET_ENABLED: "true"
    labels:
      traefik.enable: "{{ bitwarden_available_externally }}"
      traefik.http.services.bitwarden.loadbalancer.server.port: "80"
      traefik.http.middlewares.bitwarden-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.bitwarden-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.bitwarden.middlewares: "bitwarden-whitelist"
      traefik.http.routers.bitwarden.rule: "Host(`bitwarden.{{ ansible_nas_domain }}`)"
      traefik.http.routers.bitwarden.service: "bitwarden"
      traefik.http.routers.bitwarden-websocket.rule: "Host(`bitwarden.{{ ansible_nas_domain }}`) && Path(`/notifications/hub`)"
      traefik.http.routers.bitwarden-websocket.middlewares: "bitwarden-whitelist"
      traefik.http.services.bitwarden-websocket.loadbalancer.server.port: "3012"
      traefik.http.routers.bitwarden-websocket.service : "bitwarden-websocket"
      com.centurylinklabs.watchtower.enable: "{{ bitwarden_watchtower_enable }}"
    restart_policy: unless-stopped
    #memory: 1g

- name: Bitwarden Backup Container
  docker_container:
    name: bitwarden-backup
    image: bruceforce/bw_backup:latest
    pull: true
    restart_policy: unless-stopped
    volumes_from: bitwarden
    labels:
      traefik.enable: "false"
    memory: 1g
