---
- name: Create booksonic Directory
  file:
    path: "{{ booksonic_data_directory }}"
    state: directory

- name: booksonic
  docker_container:
    name: booksonic
    image: linuxserver/booksonic
    pull: true
    volumes:
      - "{{ booksonic_audiobooks_directory }}:/audiobooks:rw"
      - "{{ booksonic_podcasts_directory }}:/podcasts:rw"
      - "{{ booksonic_othermedia_directory }}:/othermedia:rw"
      - "{{ booksonic_downloads_directory }}:/downloads:rw"
      - "{{ booksonic_data_directory }}:/config:rw"
    ports:
      - "{{ booksonic_port }}:4040"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ booksonic_user_id }}"
      PGID: "{{ booksonic_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ booksonic_available_externally }}"
      traefik.http.services.booksonic.loadbalancer.server.port: "4040"
      traefik.http.middlewares.booksonic-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.booksonic-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.booksonic.middlewares: "booksonic-whitelist"
      traefik.http.routers.booksonic.rule: "Host(`booksonic.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ booksonic_watchtower_enable }}"
