- name: Create Calibre Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ calibre_data_directory }}/config"

- name: Calibre Docker Container
  docker_container:
    name: calibre
    image: linuxserver/calibre-web:latest
    pull: true
    volumes:
      - "{{ calibre_data_directory }}/config:/config"
      - "{{ calibre_books_root }}:/books"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ calibre_user_id }}"
      PGID: "{{ calibre_group_id }}"
      DOCKER_MODS: "{{ calibre_ebook_conversion }}"
    ports:
      - "{{ calibre_port }}:8083"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "{{ calibre_available_externally }}"
      traefik.http.services.calibre.loadbalancer.server.port: "8083"
      traefik.http.middlewares.calibre-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.calibre-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.calibre.middlewares: "calibre-whitelist"
      traefik.http.routers.calibre.rule: "Host(`calibre.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ calibre_watchtower_enable }}"
    memory: 1g