---
- name: Create Couchpotato Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ docker_home }}/couchpotato/config"

- name: Couchpotato Docker Container
  docker_container:
    name: couchpotato
    image: linuxserver/couchpotato
    pull: true
    volumes:
      - "{{ couchpotato_config_directory }}:/config:rw"
      - "{{ couchpotato_downloads_directory }}:/downloads:rw"
      - "{{ couchpotato_movies_directory }}:/movies:rw"
      - "{{ couchpotato_torrents_directory }}:/torrents:rw"
    ports:
      - "{{ couchpotato_port }}:5050"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ couchpotato_user_id }}"
      PGID: "{{ couchpotato_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ couchpotato_available_externally }}"
      traefik.http.services.couchpotato.loadbalancer.server.port: "5050"
      traefik.http.middlewares.couchpotato-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.couchpotato-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.couchpotato.middlewares: "couchpotato-whitelist"
      traefik.http.routers.couchpotato.rule: "Host(`couchpotato.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ couchpotato_watchtower_enable }}"