---
- name: Create Duplicati Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ duplicati_data_directory }}"

- name: Dupicati Docker Container
  docker_container:
    name: duplicati
    image: linuxserver/duplicati
    pull: true
    ports:
      - "{{ duplicati_port }}:8200"
    volumes:
      - "{{ duplicati_data_directory }}:/config:rw"
      - "{{ samba_shares_root }}:/source/shares:ro"
      - "{{ docker_home }}:/source/docker:ro"
      - "/etc/timezone:/etc/timezone:ro"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ duplicati_available_externally }}"
      traefik.http.services.duplicati.loadbalancer.server.port: "8200"
      traefik.http.middlewares.duplicati-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.duplicati-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.duplicati.middlewares: "duplicati-whitelist"
      traefik.http.routers.duplicati.rule: "Host(`duplicati.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ duplicati_watchtower_enable }}"
