- name: Create Firefly III Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ firefly_data_directory }}/postgresql"
    - "{{ firefly_data_directory }}/mysql"
    - "{{ firefly_data_directory }}/upload"
    - "{{ firefly_data_directory }}/export"

- name: Create MySQL container for Firefly
  docker_container:
    name: firefly-mysql
    image: mysql:5.7
    pull: true
    volumes:
      - "{{ firefly_data_directory }}/mysql:/var/lib/mysql:rw"
    env:
      MYSQL_DATABASE: "firefly"
      MYSQL_USER: "firefly"
      MYSQL_PASSWORD: "firefly"
      MYSQL_ROOT_PASSWORD: "firefly"
    labels:
      traefik.enable: "false"
    restart_policy: unless-stopped
    memory: 1g

- name: Wait for MySQL to init
  pause:
    seconds: 30

- name: Create Firefly III container
  docker_container:
    name: firefly
    image: jc5x/firefly-iii:latest
    pull: true
    volumes:
      - "{{ firefly_data_directory }}/export:/var/www/firefly-iii/storage/export:rw"
      - "{{ firefly_data_directory }}/upload:/var/www/firefly-iii/storage/upload:rw"
    links:
      - firefly-mysql:db
    ports:
      - "{{ firefly_port }}:8080"
    env:
      APP_ENV: "local"
      APP_KEY: "S0m3R@nd0mString0f32Ch@rsEx@ct1y"
      TRUSTED_PROXIES: "**"
      DB_CONNECTION: "mysql"
      DB_HOST: "db"
      DB_DATABASE: "firefly"
      DB_USERNAME: "firefly"
      DB_PASSWORD: "firefly"
      TZ: "{{ ansible_nas_timezone }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ firefly_available_externally }}"
      traefik.http.services.firefly.loadbalancer.server.port: "8080"
      traefik.http.middlewares.firefly-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.firefly-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.firefly.middlewares: "firefly-whitelist"
      traefik.http.routers.firefly.rule: "Host(`firefly.{{ ansible_nas_domain }}`)"
      #traefik.http.middlewares.firefly-redirect.redirectScheme.scheme: "https"
      #traefik.http.middlewares.firefly-header.headers.forceSTSHeader: "true"
      #traefik.http.middlewares.firefly-header.headers.accesscontrolalloworiginlist: "https://firefly.{{ ansible_nas_domain }}"
      com.centurylinklabs.watchtower.enable: "{{ firefly_watchtower_enable }}"

- name: Create Firefly III CSV Importer container
  docker_container:
    name: firefly-csv
    image: fireflyiii/csv-importer
    pull: true
    volumes:
      - "{{ fireflycsv_data_directory }}/configurations:/var/www/html/storage/configurations:rw"
    ports:
      - "{{ fireflycsv_port }}:8080"
    env:
      FIREFLY_III_ACCESS_TOKEN: "{{ fireflycsv_access_token }}"
      FIREFLY_III_URL: "http://firefly.{{ ansible_nas_domain }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ fireflycsv_available_externally }}"
      traefik.http.services.firefly.loadbalancer.server.port: "8080"
      traefik.http.middlewares.firefly-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.firefly-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.firefly.middlewares: "fireflycsv-whitelist"
      traefik.http.routers.firefly.rule: "Host(`fireflycsv.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ fireflycsv_watchtower_enable }}"