---
- name: Create Flarum Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ flarum_data_directory }}"

- name: Flarum Container
  docker_container:
    name: flarum
    image: crazymax/flarum:latest
    pull: true
    ports:
      - "{{ flarum_port }}:8000"
    links:
      - mariadb:db
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ flarum_user_id }}"
      PGID: "{{ flarum_group_id }}"
      MEMORY_LIMIT: "{{ flarum_memory_limit }}" #PHP memory limit (default 256M)
      UPLOAD_MAX_SIZE: "{{ flarum_max_upload_size }}" #Upload max size (default 16M)
      CLEAR_ENV: "{{ flarum_clear_env }}" #Clear environment in FPM workers (default yes)
      OPCACHE_MEM_SIZE: "{{ flarum_php_opcache }}" #PHP OpCache memory consumption (default 128)
      LISTEN_IPV6: "{{ flarum_enable_ipv6 }}" #Enable IPv6 for Nginx (default true)
      REAL_IP_FROM: "{{ flarum_real_ip_from }}" #Trusted addresses that are known to send correct replacement addresses (default 0.0.0.0/32)
      REAL_IP_HEADER: "{{ flarum_real_ip_header }}" #Request header field whose value will be used to replace the client address (default X-Forwarded-For)
      LOG_IP_VAR: "{{ flarum_log_ip_var }}" #Use another variable to retrieve the remote IP address for access log_format on Nginx. (default remote_addr)
      FLARUM_DEBUG: "{{ flarum_debug }}" #Enables or disables debug mode, used to troubleshoot issues (default false)
      FLARUM_BASE_URL: "{{ flarum_base_url }}" #The URL to your Flarum installation required
      FLARUM_FORUM_TITLE: "{{ flarum_forum_title }}" #Flarum forum title, only used during first installation (default Flarum Dockerized)
      FLARUM_API_PATH: "{{ flarum_api_path }}" #Flarum api path (default api)
      FLARUM_ADMIN_PATH: "{{ flarum_admin_path }}" #Flarum admin path (default admin)
      DB_HOST: "{{ flarum_db_host }}" #MySQL database hostname / IP address required
      DB_PORT: "{{ flarum_db_port }}" #MySQL database port (default 3306)
      DB_NAME: "{{ flarum_db_name }}" #MySQL database name (default flarum)
      DB_USER: "{{ flarum_db_user }}" #MySQL user (default flarum)
      DB_PASSWORD: "{{ flarum_db_password }}" #MySQL password
      DB_PREFIX: "{{ flarum_db_prefix }}" #MySQL database prefix (default flarum_)
      DB_TIMEOUT: "{{ flarum_db_timeout }}" #Time in seconds after which we stop trying to reach the MySQL server (useful for clusters, default 60)

    volumes:
      - "{{ flarum_data_directory }}:/data:rw"
      - "/etc/timezone:/etc/timezone:ro"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ flarum_available_externally }}"
      traefik.http.services.flarum.loadbalancer.server.port: "8000"
      traefik.http.middlewares.flarum-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.flarum-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.flarum.middlewares: "flarum-whitelist"
      traefik.http.routers.flarum.rule: "Host(`flarum.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ flarum_watchtower_enable }}"

- name: Add PL language pack
  shell: docker exec flarum composer require rob006/flarum-lang-polish
- name: Add fof/formatting
  shell: docker exec flarum composer require fof/formatting
- name: Add fof/links
  shell: docker exec flarum composer require fof/links
- name: Add fof/polls
  shell: docker exec flarum composer require fof/polls
- name: Add fof/byobu
  shell: docker exec flarum composer require "fof/byobu:*"
- name: Add fof/merge discussions
  shell: docker exec flarum composer require fof/merge-discussions
- name: Add fof/follow-tags
  shell: docker exec flarum composer require fof/follow-tags
- name: Add fof/reactions
  shell: docker exec flarum composer require fof/reactions
- name: Add fof/split
  shell: docker exec flarum composer require "fof/split:*"
- name: Add summaries
  shell: docker exec flarum composer require jordanjay29/flarum-ext-summaries
- name: Add fof/subscribed
  shell: docker exec flarum composer require "fof/subscribed:*"


