- name: Mount a downloads share
  ansible.posix.mount:
    src: //zyxel/admin/download
    path: "{{ downloads_root }}"
    fstype: cifs
    opts: vers=1.0,user={{ downloads_user }},noserverino,dir_mode=0775,password={{ downloads_password }},file_mode=0775,uid=anarion-nas,gid=anarion-nas
    state: mounted