- name: Create get_iplayer Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ get_iplayer_config_directory }}"
    - "{{ get_iplayer_download_directory }}"

- name: get_iplayer Docker Container
  docker_container:
    name: get_iplayer
    image: kolonuk/get_iplayer
    pull: true
    volumes:
      - "{{ get_iplayer_config_directory }}:/root/.get_iplayer:rw"
      - "{{ get_iplayer_download_directory }}:/root/output:rw"
    ports:
      - "{{ get_iplayer_port }}:8181"
    labels:
      traefik.enable: "{{ get_iplayer_available_externally }}"
      traefik.http.services.get_iplayer.loadbalancer.server.port: "8181"
      traefik.http.middlewares.get_iplayer-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.get_iplayer-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.get_iplayer.middlewares: "get_iplayer-whitelist"
      traefik.http.routers.get_iplayer.rule: "Host(`get_iplayer.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ get_iplayer_watchtower_enable }}"
    restart_policy: unless-stopped
    memory: 1g

