- name: Create Ghost Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ghost_data_directory }}"

- name: ghost Docker Container
  docker_container:
    name: ghost
    image: ghost
    pull: true
    container_default_behavior: no_defaults
    ports:
      - "{{ ghost_port }}:2368"
    volumes:
      - "{{ ghost_data_directory }}/content:/var/lib/ghost/content:rw"
    networks:
      - name: "traefik_internal"
    network_mode: "traefik_internal"
    env:
      url: "{{ ghost_url }}"
      database__client: "{{ ghost_db_client }}"
      database__connection__host: "{{ ghost_db_host }}"
      database__connection__user: "{{ ghost_db_user }}"
      database__connection__password: "{{ ghost_db_password }}"
      database__connection__database: "{{ ghost_db_database }}"
      mail__from: "{{ ghost_mail_from }}"
      mail__transport: "{{ ghost_mail_transport }}"
      mail__options__service: "{{ ghost_mail_options_service }}"
      mail__options__host: "{{ ghost_mail_options_host}}"
      mail__options__port: "{{ ghost_mail_options_port }}"
      mail__options__secureConnection: "{{ ghost_mail_options_secure }}"
      mail__options__auth__user: "{{ ghost_mail_options_auth }}"
      mail__options__auth__pass: "{{ ghost_mail_options_pass }}"
    labels:
      traefik.enable: "{{ ghost_available_externally }}"
      traefik.http.services.ghost.loadbalancer.server.port: "2368"
      traefik.http.middlewares.ghost-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.ghost-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.ghost.middlewares: "ghost-whitelist"
      traefik.http.routers.ghost.rule: "Host(`ghost.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ ghost_watchtower_enable }}"
    restart_policy: unless-stopped
    #memory: 1g

- name: ghost db Docker Container
  docker_container:
    name: ghost_db
    image: mysql:8.0
    pull: true
    container_default_behavior: no_defaults
    volumes:
      - "{{ ghost_data_directory }}/db:/var/lib/mysql:rw"
    networks:
      - name: "traefik_internal"
    network_mode: "traefik_internal"
    env:
      MYSQL_ROOT_PASSWORD: "{{ ghost_mysql_root_password }}"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "false"
      com.centurylinklabs.watchtower.enable: "{{ ghost_watchtower_enable }}"
