- name: Glances Docker Container
  docker_container:
    name: glances
    image: nicolargo/glances
    pull: true
    ports:
      - "{{ glances_port_one }}:61208"
      - "{{ glances_port_two }}:61209"
    volumes:
      #- "/glances.conf:/glances/conf/glances.conf"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/timezone:/etc/timezone:ro"
    pid_mode: host
    network_mode: host
    env:
      GLANCES_OPT: "-w"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ glances_available_externally }}"
      traefik.http.services.glances.loadbalancer.server.port: "61208"
      traefik.http.middlewares.glances-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.glances-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.glances.middlewares: "glances-whitelist"
      traefik.http.routers.glances.rule: "Host(`glances.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ glances_watchtower_enable }}"