---
- name: Create Gotify Data Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ gotify_data_directory }}"

- name: Gotify Docker Container
  docker_container:
    name: gotify
    image: "{{ gotify_docker_image }}"
    pull: true
    ports:
      - "{{ gotify_port }}:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ gotify_data_directory }}:/app/data:rw"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ gotify_user_id }}"
      PGID: "{{ gotify_group_id }}"
    restart_policy: unless-stopped
    memory: "{{ gotify_memory }}"
    labels:
      traefik.enable: "{{ gotify_available_externally }}"
      traefik.http.routers.gotify.rule: "Host(`{{ gotify_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.services.gotify.loadbalancer.server.port: "80"
      traefik.http.middlewares.gotify-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.gotify-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.gotify.middlewares: "gotify-whitelist"
      com.centurylinklabs.watchtower.enable: "{{ gotify_watchtower_enable }}"