---
- name: Create Grocy Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ grocy_data_directory }}"

- name: Grocy
  docker_container:
    name: grocy
    image: linuxserver/grocy
    pull: true
    volumes:
      - "{{ grocy_data_directory }}:/config:rw"
    ports:
      - "{{ grocy_port }}:80"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ grocy_user_id }}"
      PGID: "{{ grocy_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "grocy"
      traefik.frontend.rule: "Host:grocy.{{ ansible_nas_domain }}"
      traefik.enable: "{{ grocy_available_externally }}"
      traefik.port: "9283"
      com.centurylinklabs.watchtower.enable: "{{ grocy_watchtower_enable }}"