---
- name: Create Grocy Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ grocy_data_directory }}"

- name: Grocy
  docker_container:
    name: grocy
    image: linuxserver/grocy
    pull: true
    volumes:
      - "{{ grocy_data_directory }}:/config:rw"
    ports:
      - "{{ grocy_port }}:80"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ grocy_user_id }}"
      PGID: "{{ grocy_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ grocy_available_externally }}"
      traefik.http.services.grocy.loadbalancer.server.port: "80"
      traefik.http.middlewares.grocy-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.grocy-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.grocy.middlewares: "grocy-whitelist"
      traefik.http.routers.grocy.rule: "Host(`grocy.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ grocy_watchtower_enable }}"