- name: Create Home Assistant Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ homeassistant_data_directory }}/config"

- name: Home Assistant Docker Container
  docker_container:
    name: homeassistant
    image: homeassistant/home-assistant
    pull: true
    volumes:
      - "{{ homeassistant_data_directory }}/config:/config:rw"
    network_mode: host
    restart_policy: unless-stopped
    env:
      TZ: "{{ ansible_nas_timezone }}"
    labels:
      traefik.enable: "{{ homeassistant_available_externally }}"
      traefik.http.services.homeassistant.loadbalancer.server.port: "8123"
      traefik.http.middlewares.whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.2.0/16"
      traefik.http.routers.homeassistant.middlewares: "whitelist"
      traefik.http.routers.homeassistant.rule: "Host(`homeassistant.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ homeassistant_watchtower_enable }}"
    memory: 1g
