---
- name: Create Huginn Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ huginn_data_directory }}"

- name: Huginn
  docker_container:
    name: huginn
    image: huginn/huginn
    pull: true
    volumes:
      - "{{ huginn_data_directory }}:/config:rw"
    ports:
      - "{{ huginn_port }}:80"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ huginn_user_id }}"
      PGID: "{{ huginn_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ huginn_available_externally }}"
      traefik.http.services.huginn.loadbalancer.server.port: "80"
      traefik.http.middlewares.whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.2.0/16"
      traefik.http.routers.huginn.middlewares: "whitelist"
      traefik.http.routers.huginn.rule: "Host(`huginn.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ huginn_watchtower_enable }}"