---
- name: Create jackett Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ jackett_data_directory }}"

- name: jackett
  docker_container:
    name: jackett
    image: linuxserver/jackett
    volumes:
      - "{{ jackett_data_directory }}:/config:rw"
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ jackett_torrents_root }}:/downloads"
    ports:
      - "{{ jackett_port }}:9117"
    env:
      TZ: "{{ ansible_nas_timezone }}"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "{{ jackett_available_externally }}"
      traefik.http.services.jackett.loadbalancer.server.port: "9117"
      traefik.http.middlewares.jackett-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.jackett-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.jackett.middlewares: "jackett-whitelist"
      traefik.http.routers.jackett.rule: "Host(`jackett.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ jackett_watchtower_enable }}"