---
- name: Create Joomla Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ joomla_data_directory }}"
    - "{{ joomla_data_directory }}/db"

- name: MySQL Docker Container for Joomla
  docker_container:
    name: joomla_mysql
    image: mysql:5.7
    pull: true
    volumes:
      - "{{ joomla_data_directory }}/db:/var/lib/mysql"
    labels:
      traefik.enable: "false"
    env:
      MYSQL_DATABASE: "joomla"
      MYSQL_USER: "joomla"
      MYSQL_ROOT_PASSWORD: "{{ joomla_database_password }}"
    restart_policy: unless-stopped
    memory: 1g

- name: Joomla Docker Container
  docker_container:
    name: joomla
    image: joomla
    pull: true
    volumes:
      - "{{ joomla_data_directory }}:/var/www/html:rw"
    ports:
      - "{{ joomla_port }}:80"
    links:
      - "joomla_mysql:mysql"
    env:
      JOOMLA_DB_HOST: "mysql"
      JOOMLA_DB_USER: "root"
      JOOMLA_DB_PASSWORD: "{{ joomla_database_password }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ joomla_available_externally }}"
      traefik.http.services.joomla.loadbalancer.server.port: "80"
      traefik.http.middlewares.joomla-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.joomla-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.joomla.middlewares: "joomla-whitelist"
      traefik.http.routers.joomla.rule: "Host(`joomla.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ joomla_watchtower_enable }}"