
---
- name: Krusader Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ krusader_config_directory }}/krusader"

- name: Krusader Docker Container
  docker_container:
    name: krusader
    image: djaydev/krusader:latest
    pull: true
    volumes:
      - "{{ krusader_config_directory }}:/config:rw"
      - "{{ krusader_browse_directory }}:/mnt/fs"
    ports:
      - "{{ krusader_port_http }}:5800"
      - "{{ krusader_port_vnc }}:5900"
    env:
      USER_ID: "{{ krusader_user_id }}"
      GROUP_ID: "{{ krusader_group_id }}"
      SECURE_CONNECTION: "{{ krusader_secure_connection }}"
      TZ: "{{ ansible_nas_timezone }}"
      VNC_PASSWORD: "{{ krusader_vnc_password }}"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "{{ krusader_available_externally }}"
      traefik.http.services.krusader.loadbalancer.server.port: "5800"
      traefik.http.middlewares.krusader-hitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.krusader-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.krusader.middlewares: "krusader-whitelist"
      traefik.http.routers.krusader.rule: "Host(`krusader.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ krusader_watchtower_enable }}"
    memory: 1g
