---
- name: Create Minetest Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ minetest_data_directory }}/config"

- name: Minetest
  docker_container:
    name: minetest
    image: linuxserver/minetest
    pull: true
    volumes:
      - "{{ minetest_data_directory }}/config:/config/.minetest:rw"
    ports:
      - "{{ minetest_port_http }}:30000/tcp"
      - "{{ minetest_port_http }}:30000/udp"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ minetest_user_id }}"
      PGID: "{{ minetest_group_id }}"
      CLI_ARGS: "--gameid minetest" #optional
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ minetest_available_externally }}"
      traefik.http.services.minetest.loadbalancer.server.port: "30000"
      traefik.http.middlewares.minetest-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.minetest-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.minetest.middlewares: "minetest-whitelist"
      traefik.http.routers.minetest.rule: "Host(`minetest.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ minetest_watchtower_enable }}"
