---
- name: Create Mylar Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ mylar_data_directory }}/config"

- name: Mylar
  docker_container:
    name: mylar
    image: hotio/mylar3
    pull: true
    volumes:
      - "{{ mylar_comics_directory }}:/comics:rw"
      - "{{ mylar_downloads_directory }}:/downloads:rw"
      - "{{ mylar_data_directory }}/config:/config:rw"
    ports:
      - "{{ mylar_port_http }}:8090"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ mylar_user_id }}"
      PGID: "{{ mylar_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ mylar_available_externally }}"
      traefik.http.services.mylar.loadbalancer.server.port: "8090"
      traefik.http.middlewares.mylar-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.mylar-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.mylar.middlewares: "mylar-whitelist"
      traefik.http.routers.mylar.rule: "Host(`mylar.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ mylar_watchtower_enable }}"
