---
- name: netbootxyz Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ netbootxyz_config_directory }}"
    - "{{ netbootxyz_assets_directory }}"

- name: netbootxyz Docker Container
  docker_container:
    name: netbootxyz
    image: linuxserver/netbootxyz:latest
    pull: true
    volumes:
      - "{{ netbootxyz_config_directory }}:/config:rw"
      - "{{ netbootxyz_assets_directory }}:/assets:rw"
    ports:
      - "{{ netbootxyz_port_http }}:3000"
      - "{{ netbootxyz_port_http2 }}:80"
      - "{{ netbootxyz_port_tftp }}:69/udp"
    memory: "{{ netbootxyz_memory }}"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ netbootxyz_user_id }}"
      PGID: "{{ netbootxyz_group_id }}"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "{{ netbootxyz_available_externally }}"
      traefik.http.routers.netbootxyz.rule: "Host(`{{ netbootxyz_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.middlewares.netbootxyz-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.netbootxyz-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.netbootxyz.middlewares: "netbootxyz-whitelist"
      com.centurylinklabs.watchtower.enable: "{{ netbootxyz_watchtower_enable }}"
      traefik.http.services.netbootxyz.loadbalancer.server.port: "80"