---
- name: Create NZBget Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nzbget_data_directory }}"

- name: NZBGet
  docker_container:
    name: nzbget
    image: linuxserver/nzbget
    pull: true
    volumes:
      - "{{ nzbget_download_directory }}:/downloads:rw"
      - "{{ nzbget_data_directory }}:/config:rw"
    ports:
      - "{{ nzbget_port }}:6789"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ nzbget_user_id }}"
      PGID: "{{ nzbget_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ nzbget_available_externally }}"
      traefik.http.services.nzbget.loadbalancer.server.port: "6789"
      traefik.http.middlewares.whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.2.0/16"
      traefik.http.routers.nzbget.middlewares: "whitelist"
      traefik.http.routers.nzbget.rule: "Host(`nzbget.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ nzbget_watchtower_enable }}"