---
- name: Create NzbHydra2 Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nzbhydra2_data_directory }}"

- name: Nzbhydra2
  docker_container:
    name: nzbhydra2
    image: linuxserver/nzbhydra2
    pull: true
    volumes:
      - "{{ nzbhydra2_data_directory }}:/config:rw"
      - "{{ nzbhydra2_download_directory }}:/downloads:rw"
    ports:
      - "{{ nzbhydra2_port }}:5076"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ nzbhydra2_user_id }}"
      PGID: "{{ nzbhydra2_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ nzbhydra2_available_externally }}"
      traefik.http.services.nzbhydra2.loadbalancer.server.port: "5076"
      traefik.http.middlewares.whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.2.0/16"
      traefik.http.routers.nzbhydra2.middlewares: "whitelist"
      traefik.http.routers.nzbhydra2.rule: "Host(`nzbhydra2.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ nzbhydra2_watchtower_enable }}"
