---
- name: Create NzbHydra2 Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nzbhydra2_data_directory }}"
    
- name: Nzbhydra2
  docker_container:
    name: nzbhydra2
    image: linuxserver/nzbhydra2
    pull: true
    volumes:
      - "{{ nzbhydra2_data_directory }}:/config:rw"
    ports:
      - "{{ nzbhydra2_port }}:5076"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ nzbhydra2_user_id }}"
      PGID: "{{ nzbhydra2_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "nzbhydra2"
      traefik.frontend.rule: "Host:nzbhydra2.{{ ansible_nas_domain }}"
      traefik.enable: "{{ nzbhydra2_available_externally }}"
      traefik.port: "5076"
      