---
- name: Create ombi Directories
  file:
    path: "{{ ombi_config_directory }}"
    state: directory

- name: ombi
  docker_container:
    name: ombi
    image: linuxserver/ombi
    pull: true
    volumes:
      - "{{ ombi_config_directory }}:/config:rw"
    ports:
      - "3579:3579"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ ombi_user_id }}"
      PGID: "{{ ombi_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ ombi_available_externally }}"
      traefik.http.services.ombi.loadbalancer.server.port: "3579"
      traefik.http.middlewares.whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.2.0/16"
      traefik.http.routers.ombi.middlewares: "whitelist"
      traefik.http.routers.ombi.rule: "Host(`ombi.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ ombi_watchtower_enable }}"