---
- name: Create OpenLDAP Directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "{{ openldap_data_directory }}/data"

- name: OpenLDAP
  docker_container:
    name: openldap
    image: bitnami/openldap
    pull: true
    networks:
      - name: "traefik_internal"
    volumes:
      - "{{ openldap_data_directory }}:/bitnami/openldap"
    ports:
      - '{{ openldap_port }}:1389'
      - '{{ openldap_port_ssl }}:1636'
    env:
      TZ: "{{ ansible_nas_timezone }}"
      LDAP_ROOT: "{{ openldap_ldap_root }}"
      LDAP_ADMIN_USERNAME: "{{ openldap_admin_username }}"
      LDAP_ADMIN_PASSWORD: "{{ openldap_admin_password }}"
      LDAP_USERS: "{{ openldap_ldap_users }}"
      LDAP_PASSWORDS: "{{ openldap_ldap_passwords }}"
      LDAP_USER_DC: "{{ openldap_ldap_user_dc }}"
      LDAP_GROUP: "{{ openldap_ldap_group }}"
      LDAP_SKIP_DEFAULT_TREE: "{{ openldap_ldap_skip_default_tree }}"
      LDAP_ALLOW_ANON_BINDING: "{{ openldap_ldap_allow_anon_binding }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ openldap_available_externally }}"
      com.centurylinklabs.watchtower.enable: "{{ openldap_watchtower_enable }}"

- name: phpLDAPadmin
  docker_container:
    name: phpldapadmin
    image: osixia/phpldapadmin
    networks:
      - name: "traefik_internal"
    pull: true
    volumes:
      - "{{ openldap_data_directory }}/lib:/var/lib/ldap:rw"
      - "{{ openldap_data_directory }}/config:/etc/ldap/slapd.d:rw"
    ports:
      - "{{ phpldapadmin_port }}:443"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'openldap': [{'server': [{'port': 1389 }]}]}]"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ phpldapadmin_available_externally }}"
      traefik.http.services.phpldapadmin.loadbalancer.server.port: "443"
      traefik.http.middlewares.phpldapadmin-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.phpldapadmin-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.phpldapadmin.middlewares: "phpldapadmin-whitelist"
      traefik.http.routers.phpldapadmin.rule: "Host(`phpldapadmin.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ phpldapadmin_watchtower_enable }}"

# - name: Create PLA template directory
#   ansible.builtin.file:
#     path: "{{ openldap_data_directory }}/config/templates"
#     state: directory
#     mode: '0755'

# - name: Copy all templates
#   copy:
#     src: "{{ item }}"
#     dest: "{{ openldap_data_directory }}/config/templates"
#     #mode: u=rw, g=rw, o=r
#   with_fileglob:
#     - "phpldapadmin/templates/*"

- name: Copy PLA templates to container
  shell: docker cp files/phpldapadmin/templates/* phpldapadmin:/var/www/phpldapadmin/templates/creation/

- name: Update template permissions
  shell: docker exec phpldapadmin chown -R www-data:www-data /var/www/phpldapadmin/templates/creation/