
---
- name: Create Organizr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ organizr_data_directory }}"

- name: Create Organizr container
  docker_container:
    name: organizr
    image: organizrtools/organizr-v2:latest
    pull: true
    volumes:
      - "{{ organizr_data_directory }}:/config:rw"
    env:
      PUID: "{{ organizr_user_id }}"
      PGID: "{{ organizr_group_id }}"
      TZ: "{{ ansible_nas_timezone }}"
    ports:
      - "{{ organizr_port_http }}:80"
      - "{{ organizr_port_https }}:443"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ organizr_available_externally }}"
      traefik.http.services.organizr.loadbalancer.server.port: "80"
      traefik.http.middlewares.whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.2.0/16"
      traefik.http.routers.organizr.middlewares: "whitelist"
      traefik.http.routers.organizr.rule: "Host(`organizr.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ organizr_watchtower_enable }}"
