- name: Create Plex Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ plex_config_directory }}"
    - "{{ plex_logs }}"

- name: plex Docker Container
  docker_container:
    name: plex
    image: linuxserver/plex
    pull: true
    volumes:
      - "{{ plex_config_directory }}:/config:rw"
      - "{{ plex_logs }}:/opt/plex/Library/Application Support/Plex Media Server/Logs:rw"
      - "{{ plex_movies_directory }}:/movies:{{ plex_movies_permissions }}"
      - "{{ plex_tv_directory }}:/tv:{{ plex_tv_permissions }}"
      - "{{ plex_photos_directory }}:/photos:{{ plex_photos_permissions }}"
      - "{{ plex_podcasts_directory }}:/podcasts:{{ plex_podcasts_permissions }}"
      - "{{ plex_music_directory }}:/music:{{ plex_music_permissions }}"
    pull: true
    ports:
      - "{{ plex_port }}:32400"
      - "5353:5353/udp"
      - "32400:32400/tcp"
      - "32400:32400/udp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ plex_user_id }}"
      PGID: "{{ plex_group_id }}"
    restart_policy: unless-stopped
    memory: 2g
    labels:
      traefik.enable: "{{ plex_available_externally }}"
      traefik.http.services.plex.loadbalancer.server.port: "32400"
      traefik.http.middlewares.plex-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.plex-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.plex.middlewares: "plex-whitelist"
      traefik.http.routers.plex.rule: "Host(`plex.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ plex_watchtower_enable }}"
