---
- name: Create Portainer Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ portainer_data_directory }}"

- name: Portainer Docker Container
  docker_container:
    name: portainer
    image: portainer/portainer
    pull: true
    volumes:
      - "{{ portainer_data_directory }}:/data:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "{{ portainer_port }}:9000"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ portainer_available_externally }}"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
      traefik.http.middlewares.portainer-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.portainer-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.portainer.middlewares: "portainer-whitelist"
      traefik.http.routers.portainer.rule: "Host(`portainer.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ portainer_watchtower_enable }}"