---
- name: Create Prowlarr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ prowlarr_data_directory }}"

- name: prowlarr
  docker_container:
    name: prowlarr
    image: ghcr.io/linuxserver/prowlarr:develop
    pull: true
    volumes:
      - "{{ prowlarr_data_directory }}:/config:rw"
    ports:
      - "{{ prowlarr_port }}:9696"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ prowlarr_user_id }}"
      PGID: "{{ prowlarr_group_id }}"
    restart_policy: unless-stopped
    memory: "{{ prowlarr_memory }}"
    labels:
      traefik.enable: "{{ prowlarr_available_externally }}"
      traefik.http.routers.prowlarr.rule: "Host(`{{ prowlarr_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.services.prowlarr.loadbalancer.server.port: "9696"
      traefik.http.middlewares.prowlarr-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.prowlarr-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.prowlarr.middlewares: "prowlarr-whitelist"
      com.centurylinklabs.watchtower.enable: "{{ prowlarr_watchtower_enable }}"