---
- name: PyTivo - create config directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "{{ pytivo_config_directory }}"

- name: PyTivo - install Docker container
  docker_container:
    name: pytivo
    image: pinion/docker-pytivo
    pull: true
    ports:
      - "9032:9032"
      - "2190:2190/udp"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ pytivo_config_directory }}:/config:rw"
      - "{{ pytivo_movies_directory }}:/movies:ro"
      - "{{ pytivo_tv_directory }}:/tv:ro"
      - "{{ pytivo_photos_directory }}:/photos:ro"
      - "{{ pytivo_music_directory }}:/music:ro"
      - "{{ pytivo_podcasts_directory }}:/podcasts:ro"
    network_mode: "host"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ pytivo_user_id }}"
      PGID: "{{ pytivo_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ pytivo_available_externally }}"
      traefik.http.services.pytivo.loadbalancer.server.port: "9032"
      traefik.http.middlewares.whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.2.0/16"
      traefik.http.routers.pytivo.middlewares: "whitelist"
      traefik.http.routers.pytivo.rule: "Host(`pytivo.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ pytivo_watchtower_enable }}"
