---
- name: Create Shaarli Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "{{ shaarli_data_directory }}/data"

- name: Shaarli Docker Container
  docker_container:
    name: shaarli
    image: shaarli/shaarli
    pull: true
    volumes:
      - "{{ shaarli_data_directory }}/data:/var/www/shaarli/data:rw"
    ports:
      - "{{ shaarli_port }}:80"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ shaarli_user_id }}"
      PGID: "{{ shaarli_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ shaarli_available_externally }}"
      traefik.http.services.shaarli.loadbalancer.server.port: "80"
      traefik.http.middlewares.shaarli-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.shaarli-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.shaarli.middlewares: "shaarli-whitelist"
      traefik.http.routers.shaarli.rule: "Host(`shaarli.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ shaarli_watchtower_enable }}"
