---
- name: Create Sonarr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ sonarr_data_directory }}"

- name: Sonarr
  docker_container:
    name: sonarr
    image: linuxserver/sonarr
    pull: true
    volumes:
      - "{{ sonarr_tv_directory }}:/tv:rw"
      - "{{ sonarr_download_directory }}:/downloads:rw"
      - "{{ sonarr_data_directory }}:/config:rw"
    ports:
      - "{{ sonarr_port }}:8989"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ sonarr_user_id }}"
      PGID: "{{ sonarr_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ sonarr_available_externally }}"
      traefik.http.services.sonarr.loadbalancer.server.port: "8989"
      traefik.http.middlewares.whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.2.0/16"
      traefik.http.routers.sonarr.middlewares: "whitelist"
      traefik.http.routers.sonarr.rule: "Host(`sonarr.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ sonarr_watchtower_enable }}"