---
- name: Create InfluxDB and Telegraf Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ influxdb_data_directory }}"
    - "{{ telegraf_data_directory }}"

- name: Create Grafana Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "472"
    recurse: yes
  with_items:
    - "{{ grafana_data_directory }}"
    - "{{ grafana_data_directory }}/data"
    - "{{ grafana_data_directory }}/data/dashboards/anarion-nas"
    - "{{ grafana_data_directory }}/config/"
    - "{{ grafana_data_directory }}/config/provisioning"
    - "{{ grafana_data_directory }}/config/provisioning/datasources"
    - "{{ grafana_data_directory }}/config/provisioning/dashboards"

- name: InfluxDB
  docker_container:
    name: influxdb
    image: influxdb
    pull: true
    volumes:
      - "{{ influxdb_data_directory }}:/var/lib/influxdb:rw"
    ports:
      - "{{ grafana_influxdb_port }}:8086"
    restart_policy: unless-stopped
    env:
      INFLUXDB_LOGGING_LEVEL: "error"
    labels:
      com.centurylinklabs.watchtower.enable: "{{ influxdb_watchtower_enable }}"
      traefik.enable: "true"
      traefik.http.services.grafana.loadbalancer.server.port: "8086"
      traefik.http.middlewares.grafana-whitelist.ipwhitelist.ipstrategy.depth: "0"
      traefik.http.middlewares.grafana-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.grafana.middlewares: "grafana-whitelist,testHeader"
      traefik.http.routers.grafana.rule: "Host(`influxdb.{{ ansible_nas_domain }}`)"
      traefik.http.middlewares.influx-redirect.redirectScheme.scheme: "https"
      traefik.http.middlewares.testHeader.headers.forceSTSHeader: "true"
      traefik.http.middlewares.testHeader.headers.accesscontrolalloworiginlist: "https://grafana.{{ ansible_nas_domain }}"
    memory: 1g

- name: hddtemp
  docker_container:
    name: hddtemp
    image: drewster727/hddtemp-docker
    pull: true
    privileged: true
    restart_policy: unless-stopped
    env:
      HDDTEMP_ARGS: "-q -d -F /dev/sd*"
      TZ: "{{ ansible_nas_timezone }}"
    labels:
      traefik.enable: "false"
    memory: 128m

- name: Template telegraf.conf
  template:
    src: telegraf/telegraf.conf
    dest: "{{ telegraf_data_directory }}/telegraf.conf"

- name: Telegraf
  docker_container:
    name: telegraf
    image: telegraf
    pull: true
    links:
      - hddtemp:hddtemp
    privileged: true
    ipc_mode: host
    volumes:
      - "{{ telegraf_data_directory }}/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/:/hostfs:ro"
      - "/etc:/hostfs/etc:ro"
      - "/proc:/hostfs/proc:ro"
      - "/sys:/hostfs/sys:ro"
      - "/var:/hostfs/var:ro"
      - "/run:/hostfs/run:ro"
    env:
      HOST_ETC: "/hostfs/etc"
      HOST_PROC: "/hostfs/proc"
      HOST_SYS: "/hostfs/sys"
      HOST_VAR: "/hostfs/var"
      HOST_RUN: "/hostfs/run"
      HOST_MOUNT_PREFIX: "/hostfs"
    labels:
      com.centurylinklabs.watchtower.enable: "{{ telegraf_watchtower_enable }}"
      traefik.enable: "false"
    restart_policy: unless-stopped
    memory: 1g

- name: Template Grafana data source
  template:
    src: grafana/provisioning/datasources/anarion-nas.yml
    dest: "{{ grafana_data_directory }}/config/provisioning/datasources/anarion-nas.yml"

- name: Copy Anarion-NAS Dashboard Provisioner
  copy:
    src: grafana/provisioning/dashboards/anarion-nas.yml
    dest: "{{ grafana_data_directory }}/config/provisioning/dashboards/anarion-nas.yml"

- name: Copy Anarion-NAS Dashboard
  copy:
    src: grafana/dashboards/anarion-nas/anarion-nas-overview.json
    dest: "{{ grafana_data_directory }}/data/dashboards/anarion-nas/anarion-nas-overview.json"

- name: Grafana
  docker_container:
    name: grafana
    image: grafana/grafana
    pull: true
    volumes:
      - "{{ grafana_data_directory }}/data:/var/lib/grafana:rw"
      - "{{ grafana_data_directory }}/config/provisioning:/etc/grafana/provisioning:ro"
    ports:
      - "{{ grafana_port }}:3000"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ grafana_available_externally }}"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
      traefik.http.middlewares.grafana-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.grafana-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.grafana.middlewares: "grafana-whitelist"
      traefik.http.routers.grafana.rule: "Host(`grafana.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ grafana_watchtower_enable }}"