---
- name: Create Syncthing Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ syncthing_data_directory }}"

- name: Syncthing
  docker_container:
    name: syncthing
    image: linuxserver/syncthing
    pull: true
    volumes:
      - "{{ syncthing_data_directory }}:/config:rw"
    ports:
      - "{{ syncthing_webui_port }}:8384"
      - "{{ syncthing_listening_port }}:22000"
      - "{{ syncthing_discovery_port }}:21027"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ syncthing_user_id }}"
      PGID: "{{ syncthing_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "syncthing"
      traefik.frontend.rule: "Host:syncthing.{{ ansible_nas_domain }}"
      traefik.enable: "{{ syncthing_available_externally }}"
      traefik.port: "8384"
      com.centurylinklabs.watchtower.enable: "{{ syncthing_watchtower_enable }}"