---
- name: Create Syncthing Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ syncthing_data_directory }}"

- name: Syncthing
  docker_container:
    name: syncthing
    image: linuxserver/syncthing
    pull: true
    volumes:
      - "{{ syncthing_data_directory }}:/config:rw"
    ports:
      - "{{ syncthing_webui_port }}:8384"
      - "{{ syncthing_listening_port }}:22000"
      - "{{ syncthing_discovery_port }}:21027"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ syncthing_user_id }}"
      PGID: "{{ syncthing_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ syncthing_available_externally }}"
      traefik.http.services.syncthing.loadbalancer.server.port: "8384"
      traefik.http.middlewares.syncthing-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.syncthing-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.syncthing.middlewares: "syncthing-whitelist"
      traefik.http.routers.syncthing.rule: "Host(`syncthing.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ syncthing_watchtower_enable }}"