---
- name: Create Ubooquity Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ubooquity_data_directory }}"

- name: Ubooquity Docker Container
  docker_container:
    name: ubooquity
    image: linuxserver/ubooquity:latest
    pull: true
    volumes:
      - "{{ ubooquity_data_directory }}/config:/config:rw"
      - "{{ ubooquity_data_directory }}/files:/files:rw"
      - "{{ comics_root }}:/comics"
      - "{{ books_root }}:/books"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ ubooquity_user_id|quote }}"
      PGID: "{{ ubooquity_group_id|quote }}"
      MAXMEM: "1024"
    ports:
      - "{{ ubooquity_port_webui }}:2202"
      - "{{ ubooquity_port_admin }}:2203"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "{{ ubooquity_available_externally }}"
      traefik.http.services.ubooquity.loadbalancer.server.port: "2202"
      traefik.http.middlewares.ubooquity-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.ubooquity-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.ubooquity.middlewares: "ubooquity-whitelist"
      traefik.http.routers.ubooquity.rule: "Host(`ubooquity.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ ubooquity_watchtower_enable }}"
