---
- name: Create anarion-nas group
  group:
    name: anarion-nas
    state: present
    gid: 1001

- name: Create anarion-nas user
  user:
    name: anarion-nas
    state: present
    system: no
    update_password: on_create
    create_home: yes
    group: anarion-nas
    uid: 1001
    shell: /bin/bash

- name: add user account to anarion-nas group
  user:
    name: "{{ ansible_nas_user }}"
    groups: anarion-nas
    append: yes
