---
- name: Create ZNC Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ znc_data_directory }}"

- name: ZNC
  docker_container:
    name: znc
    image: znc
    pull: true
    volumes:
      - "{{ znc_data_directory }}:/znc-data:rw"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "{{ znc_port }}:6677"
    env:
      PUID: "{{ znc_user_id }}"
      PGID: "{{ znc_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ znc_available_externally }}"
      traefik.http.services.znc.loadbalancer.server.port: "6677"
      traefik.http.middlewares.znc-whitelist.ipwhitelist.ipstrategy.depth: "1"
      traefik.http.middlewares.znc-whitelist.ipwhitelist.sourcerange: "127.0.0.1/32, 192.168.0.0/16"
      traefik.http.routers.znc.middlewares: "znc-whitelist"
      traefik.http.routers.znc.rule: "Host(`znc.{{ ansible_nas_domain }}`)"
      com.centurylinklabs.watchtower.enable: "{{ znc_watchtower_enable }}"