---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Try and stop and remove tacticalrmm Postgres
      community.docker.docker_container:
        name: "{{ tacticalrmm_postgres_container_name }}"
        state: absent
      register: result_postgres

    - name: Try and stop and remove tacticalrmm Redis
      community.docker.docker_container:
        name: "{{ tacticalrmm_redis_container_name }}"
        state: absent
      register: result_redis

    - name: Try and stop and remove tacticalrmm Typesense
      community.docker.docker_container:
        name: "{{ tacticalrmm_typesense_container_name }}"
        state: absent
      register: result_typsense

    - name: Try and stop and remove tacticalrmm Server
      community.docker.docker_container:
        name: "{{ tacticalrmm_server_container_name }}"
        state: absent
      register: result_server

    - name: Try and stop and remove tacticalrmm Microservices
      community.docker.docker_container:
        name: "{{ tacticalrmm_microservices_container_name }}"
        state: absent
      register: result_microservices

    - name: Try and stop and remove tacticalrmm Machine Learning
      community.docker.docker_container:
        name: "{{ tacticalrmm_machinelearning_container_name }}"
        state: absent
      register: result_machinelearning

    - name: Try and stop and remove tacticalrmm Web
      community.docker.docker_container:
        name: "{{ tacticalrmm_web_container_name }}"
        state: absent
      register: result_web

    - name: Try and stop and remove tacticalrmm Proxy
      community.docker.docker_container:
        name: "{{ tacticalrmm_proxy_container_name }}"
        state: absent
      register: result_proxy

    - name: Check if tacticalrmm containers are stopped
      ansible.builtin.assert:
        that:
          - not result_postgres.changed
          - not result_redis.changed
          - not result_typsense.changed
          - not result_server.changed
          - not result_microservices.changed
          - not result_machinelearning.changed
          - not result_web.changed
          - not result_proxy.changed
