##                       ._____.   .__
##  _____    ____   _____|__\_ |__ |  |   ____             ____ _____    ______
##  \__  \  /    \ /  ___/  || __ \|  | _/ __ \   ______  /    \\__  \  /  ___/
##   / __ \|   |  \\___ \|  || \_\ \  |_\  ___/  /_____/ |   |  \/ __ \_\___ \
##  (____  /___|  /____  >__||___  /____/\___  >         |___|  (____  /____  >
##       \/     \/     \/        \/          \/               \/     \/     \/
##     a n s i b l e - n a s      https://github.com/davestephens/ansible-nas

# Add your all.yml config overrides to this file. See group_vars/all.yml for all possible settings.

# Example options
ansible_nas_hostname: anarion-nas
ansible_nas_timezone: Europe/Warsaw
ansible_nas_user: anarion
ansible_nas_workgroup: ANARION

## Enable some applications
#heimdall_enabled: true
#portainer_enabled: true
#organizr_enabled: true
#watchtower_enabled: true
#plex_enabled: true
#tautulli_enabled: true
#transmission_enabled: true
#pyload_enabled: true
#mylar_enabled: true
#sonarr_enabled: true
#radarr_enabled: true
#glances_enabled: true
#netdata_enabled: true
#sickchill_enabled: true
#gitea_enabled: true
#stats_enabled: true
#airsonic_enabled: true
#jackett_enabled: true
#nzbget_enabled: true
#wallabag_enabled: true
#calibre_enabled: true
#homeassistant_enabled: true
#bazarr_enabled: true
#openhab_enabled: true
#cloudcmd_enabled: true
#krusader_enabled: true
#ubooquity_enabled: true
#ombi_enabled: true
#lidarr_enabled: true
#youtubedlmaterial_enabled: true
#traefik_enabled: true
#nzbhydra2_enabled: true
#sabnzbd_enabled: true
#lazylibrarian_enabled: true
#booksonic_enabled: true
#booksonicair_enabled: true
#rclone_enabled: true
#mergerfs_enabled: true
#miniflux_enabled: true
#fstab_enabled: true
#cloud_upload_enabled: true
#plex_autoscan_enabled: true
#gaps_enabled: true
#huginn_enabled: true
#hs110_enabled: true
#snipeit_enabled: true
#shaarli_enabled: true
#nodered_enabled: true
#mariadb_enabled: true
#seafile_enabled: true
#phpmyadmin_enabled: true
#errorpages_enabled: true
#flarum_enabled: true
#restic_enabled: true
#ttrss_enabled: true
#openldap_enabled: true
#speedtest_enabled: true
#webtrees_enabled: true
#photoprism_enabled: true
#whoogle_enabled: true
#photostructure_enabled: true
#librephotos_enabled: true
#barcodebuddy_enabled: true
#beets_enabled: true
#ghost_enabled: true
#moviematch_enabled: true
#graylog_enabled: true
#netbox_enabled: true
#vaultwarden_enabled: true
#keycloak_enabled: true
#traefik_forward_auth_enabled: true
#authelia_enabled: true
#komga_enabled: true
#flame_enabled: true
#gotify_enabled: true
#prowlarr_enabled: true
#netbootxyz_enabled: true
#authentik_enabled: true
#minetest_enabled: true
#frigate_enabled: true
#plex_meta_enabled: true
#claper_enabled: true
#ssh_login_notification_enabled: true
#codex_enabled: true
#releasebell_enabled: true
#trilium_enabled: true
#immich_enabled: true
#loki_enabled: true
#photofield_enabled: true
#wger_enabled: true
#memos_enabled: true