---
role_available_externally: "{{ tiddlywiki_available_externally }}"
role_hostname: "{{ tiddlywiki_hostname }}"
role_port: "8080"
role_watchtower_enable: true

tiddlywiki_enabled: false
tiddlywiki_available_externally: false

# Data directory for config file
tiddlywiki_data_directory: "{{ docker_home }}/tiddlywiki"

# Basic auth
# tiddlywiki_username:
# tiddlywiki_password:

# Node low memory
# tiddlywiki_node_memory:

# Server debugging
# tiddlywiki_debug_level: none # full

# Networking
tiddlywiki_port: 8092
tiddlywiki_hostname: tiddlywiki

# Container
tiddlywiki_memory: 512MB
tiddlywiki_optional_labels:
  traefik.test: "True"
role_ipwhitelist_sourcerange: "32.32.32.32/16"
